spring.application.name=project
spring.datasource.url=jdbc:postgresql://localhost:5432/vitap-sell
spring.datasource.username=postgres
spring.datasource.password=3000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true